### ISSUE TITLE
Let's Encrypt SSL certificate

### ISSUE THREAD

**Issue by vogdb** [GetchaDEAGLE/gitlab-ce-https-docker#1]
Hi! As of 2023 Gitlab offers a free integration with [Let's Encrypt SSL](https://docs.gitlab.com/omnibus/settings/ssl/#enable-the-lets-encrypt-integration). It's only a matter of few config options to enable it, so there is no need to generate it on your own. What do you think if I update your repo to include this approach as well?

**Comment by danieleagle** [comment]
Thanks for being proactive and chiming in. Due to my limited bandwidth, I haven't been able to put much time into this repo. However, I definitely encourage anyone willing to provide assistance by updating and improving it for the betterment of the community to submit a pull request.

**Comment by vogdb** [comment]
Great, I will do it at the weekend!

**Comment by vogdb** [comment]
closing in favor of #2
